### ISSUE TITLE
installed the module manually - no errors. Can't see button 

### ISSUE THREAD

**Issue by ilyaIR** [magenizr/Magenizr_ResetUiBookmarks#1]
I've followed the instruction - no issues during manual install.

Magento v.2.1.8
PHP 7.x

Can't see the Reset UI Bookmark button

**Comment by magenizr** [comment]
@ilyaIR  Do you still have the problem?

**Comment by magenizr** [comment]
Please reopen the issue if you have problems with the latest version.

**Comment by amcguireweb** [comment]
I installed with composer and don't see it on the user account page. Magento Commerce 2.4.3, PHP 7.4. Any ideas?

**Comment by magenizr** [comment]
@amcguireweb 

Weird. I'll have a look tomorrow and let you know.

**Comment by amcguireweb** [comment]
@magenizr did you have a chance to take a look at this?

**Comment by magenizr** [comment]
@amcguireweb 

Seems to work fine on a vanilla 2.4.3 + php 7.4, even with different locale settings ( en_US, en_AU etc. )

```
[root@magenizr-211 current]# php -v
PHP 7.4.23 (cli) (built: Aug 24 2021 16:33:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.23, Copyright (c), by Zend Technologies
[root@magenizr-211 current]# php bin/magento --version
Magento CLI 2.4.3
```

![Screenshot from 2021-09-05 09-12-10 (1)](https://user-images.githubusercontent.com/36174840/132110209-8397fe78-06d6-41b5-8935-1ec1c02caa0b.png)

I assume you are running Magento on Linux and you did delete generated files before the deployment?

```
rm -rf ./var/cache/* generated/* ./var/session/*
rm -rf ./var/generation/*
rm -rf ./pub/static/*
```

Is there any error logged in `./var/log/*` when you hit the My Account page? Maybe ( for some reason ) the template `view/adminhtml/templates/system/account/resetuibookmarks.phtml` can be loaded. Did you set the correct file permissions for `vendor/magenizr/magento2-resetuibookmarks/`?

**Comment by amcguireweb** [comment]
Actually I'm on Magento Commerce Cloud 2.4.3 + php 7.4. Those generated files are cleared and regenerated during the redeployment of the environment.

There are no errors in var/log/*, and since I am on Magento Cloud, I don't have the ability to change or control file permissions; I would also have to assume they are correct.

Maybe it's not compatible with Magento Commerce (Enterprise)?

**Comment by magenizr** [comment]
Hi @amcguireweb 

When you have a minute, would you mind checking the following items for us? We would like to officially make it compatible with Magento Commerce Cloud. Happy to transfer you $ for coffee.

1. Has `Magenizr_ResetUiBookmarks` been enabled in `config.php`? I assume yes.
2. Is `Magenizr_ResetUiBookmarks` listed in `php bin/magento module:status`?
3. Is `Magenizr_ResetUiBookmarks` listed in `select * from setup_module where module = 'Magenizr_ResetUiBookmarks';`?
4. When you look at the backend > My Account section, does it load any assets related to "magenizr" in the network tab? It should at least load a CSS file.

Kind regards,
John

**Comment by magenizr** [comment]
Hi @amcguireweb

I'll go and close the ticket for now. Please try the most recent version, which should work in 2.4.x Commerce Cloud.
