### ISSUE TITLE
Having setup_version is redundant as there is no DB Setup

### ISSUE THREAD

**Issue by kanevbg** [magenizr/Magenizr_ResetUiBookmarks#3]
So that will save downtime because of setup:upgrade when adding the module.

**Comment by magenizr** [comment]
Hi @kanevbg 

Thank you for your feedback. We agree, the setup version is not required. A fix has been released in [1.1.2 ](https://github.com/magenizr/Magenizr_ResetUiBookmarks/releases/tag/1.1.2)

Regards,
John
