### ISSUE TITLE
Notice: Undefined variable: escaper in vendor/magenizr/magento2-resetuibookmarks/view/adminhtml/templates/system/account/resetuibookmarks.phtml on line 13

### ISSUE THREAD

**Issue by kanevbg** [magenizr/Magenizr_ResetUiBookmarks#4]
`$escaper` should be replaced with `$block`
in file `vendor/magenizr/magento2-resetuibookmarks/view/adminhtml/templates/system/account/resetuibookmarks.phtml`

**Comment by magenizr** [comment]
Hi @kanevbg 

What's your Magento version?

**Comment by kanevbg** [comment]
Hello,
2.3.7-p2

**Comment by magenizr** [comment]
Version 1.1.0 should work for you then instead of 1.1.1.

https://github.com/magenizr/Magenizr_ResetUiBookmarks/blob/1.1.0/view/adminhtml/templates/system/account/resetuibookmarks.phtml

**Comment by magenizr** [comment]
Hi @kanevbg 

Feel free to reopen the ticket if you believe something doesn't work in 2.3.x.
