### ISSUE TITLE
Make available on user management

### ISSUE THREAD

**Issue by vandijkstef** [magenizr/Magenizr_ResetUiBookmarks#5]
I was expecting this module to be available through user management (System -> All users -> [USER]). Took me a while to find out there's a seperate 'Account settings' for the logged in user in the top-right.

It would actually be great to be able to reset this for other users, as some of our warehouse accounts have very limited rights in the system.

**Comment by magenizr** [comment]
Hi @vandijkstef 

Good point, very appreciated! I think it will be a great feature to be able to cleanup bookmarks individually (System -> All users -> [USER]).

We'll go and scope this out so that is can be published in the next release.

Thanks,
John

**Comment by magenizr** [comment]
Hi @vandijkstef 

Your feature request has been released in 1.2.0. See https://github.com/magenizr/Magenizr_ResetUiBookmarks/releases/tag/1.2.0

Thanks,
John

**Comment by vandijkstef** [comment]
Just updated, many thanks for implementing this feature!
