### ISSUE TITLE
Error js validation when creating and editing users

### ISSUE THREAD

**Issue by BeardTech** [magenizr/Magenizr_ResetUiBookmarks#6]
step to reproduce: 
MAGENTO 2.4.5-P1

-> try to create a user in admin -> Save user -> get the error

![image](https://user-images.githubusercontent.com/19796076/201702306-6b453a0e-e6c0-4858-ab76-c4a2de1cb6db.png)

**Comment by magenizr** [comment]
Thanks @BeardTech 

I'll have a look and come back with an update asap.

John

**Comment by madleen** [comment]
Hi @magenizr ,
I have the same problem with the same Magento configuration as @BeardTech in developer and production mode.
If we can help you in the resolution / test do not hesitate.
Mado

**Comment by magenizr** [comment]
Thanks,

I can reproduce it and will publish a fix tonight.

John

**Comment by magenizr** [comment]
@BeardTech @madleen 

This has been fixed in 1.2.1. Thank you for reporting the issue! If you have time, check out our newest repository and share. https://github.com/magenizr/Conceal

John
