### ISSUE TITLE
Error related with PHP 8.2 

### ISSUE THREAD

**Issue by hgati** [magenizr/Magenizr_ResetUiBookmarks#8]
Clicking the "Reset UI" button results in the following error. This error occurs only in PHP 8.2 and is fixed by declaring the variable.

![](https://gcdnb.pbrd.co/images/eWU7XhjbY4TP.png)

![](https://gcdnb.pbrd.co/images/ZQQmwA13x5gt.png)

**Comment by magenizr** [comment]
Hi @hgati 

Sorry I didn't receive the notification for this issue. Looking at it now and provide an update asap.

Regards,
Magenizr

**Comment by hgati** [comment]
> Hi @hgati
> 
> Sorry I didn't receive the notification for this issue. Looking at it now and provide an update asap.
> 
> Regards, Magenizr

Thank you. I am currently using the patched version and it's working well, but It would be more convenient since I can use your repository directly if this repository could be updated.

![](https://gcdnb.pbrd.co/images/HxKrCt5lWAAb.png)

**Comment by magenizr** [comment]
Hi @hgati 

Version 1.3.1 has been released moment ago. You can remove your patch and use that version instead.

```
composer require "magenizr/magento2-resetuibookmarks":"1.3.1" --no-update
```

Thanks for reporting the issue!

Regards, John

**Comment by hgati** [comment]
Thanks for updating. @magenizr

**Comment by magenizr** [comment]
Happy to help, thanks!
